# Generated by Django 5.2.11 on 2026-04-21 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stepik_id', models.PositiveIntegerField(unique=True, verbose_name='ID на Stepik')),
                ('title', models.CharField(max_length=255, verbose_name='Название курса')),
                ('cover_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на обложку')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stepik_id', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='solutions.course')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stepik_id', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='solutions.section')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stepik_id', models.PositiveIntegerField(unique=True)),
                ('task_type', models.CharField(choices=[('choice', 'Выбор варианта'), ('string', 'Строковый ответ'), ('code', 'Программирование')], default='choice', max_length=20)),
                ('question_text', models.TextField(verbose_name='Текст задания')),
                ('correct_answer', models.TextField(verbose_name='Правильный ответ')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='solutions.lesson')),
            ],
        ),
    ]
