# Generated by Django 5.2.11 on 2026-04-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='correct_answer',
            field=models.TextField(blank=True, default='', verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='task',
            name='question_text',
            field=models.TextField(blank=True, default='', verbose_name='Текст задания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('choice', 'Выбор варианта'), ('string', 'Строковый ответ'), ('code', 'Программирование'), ('number', 'Числовой ответ'), ('math', 'Математика'), ('sorting', 'Сортировка'), ('matching', 'Сопоставление'), ('fill-blanks', 'Заполнение пропусков'), ('free-answer', 'Свободный ответ'), ('table', 'Таблица'), ('text', 'Текст/Видео'), ('other', 'Другое')], default='other', max_length=30),
        ),
    ]
