# Generated by Django 5.2.11 on 2026-04-25 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_alter_task_options_task_position_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StepikProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stepik_client_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Stepik Client ID')),
                ('stepik_client_secret', models.CharField(blank=True, default='', max_length=255, verbose_name='Stepik Client Secret')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stepik_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
