# Generated by Django 5.2.11 on 2026-04-25 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0003_stepikprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_percent', models.PositiveIntegerField(verbose_name='Целевой %')),
                ('target_score', models.IntegerField(default=0, verbose_name='Целевой балл')),
                ('current_score', models.IntegerField(default=0, verbose_name='Текущий балл')),
                ('total_score', models.IntegerField(default=0, verbose_name='Всего баллов')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('running', 'Выполняется'), ('completed', 'Завершён'), ('failed', 'Ошибка'), ('stopped', 'Остановлен')], default='pending', max_length=20, verbose_name='Статус')),
                ('log', models.TextField(blank=True, default='', verbose_name='Лог')),
                ('steps_total', models.IntegerField(default=0, verbose_name='Всего шагов')),
                ('steps_done', models.IntegerField(default=0, verbose_name='Пройдено шагов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solutions.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
